Update Tier System Icons and Formatting
sparkpointio/sparklaunch pull request #5
Opened 2021-07-14 09:47 UTC by mativanarquero

![launch_ss](https://user-images.githubusercontent.com/50922758/125601511-d151614c-8773-4a08-8014-36752f11b1d8.png)
![launch_ss_grid](https://user-images.githubusercontent.com/50922758/125601532-c57d2d8a-6e3d-433c-85b6-a25e410670e6.png)

2021-07-14 09:50 UTC, swengr-janan requested changes
![image](https://user-images.githubusercontent.com/61826@mativanarquero /125601885-040ce9c6-fde7-4253-a347-8b5fc244c9fd.png)
Pa uppercase lahat ng letters @mativanarquero

2021-07-14 10:12 UTC, kbaldo commented on src/pages/Home/AboutSection/config.ts
> +        guaranteedAllocation: 'Yes',
@mativanarquero, kuya @swengr-janan requested to capitalize all the letters. So far, it seems like yung `Y` palang from `Yes` is capitalized haha

2021-07-14 10:13 UTC, swengr-janan commented on src/pages/Home/AboutSection/config.ts
> +        guaranteedAllocation: 'Yes',
Yep, ilahat mo na @mativanarquero .

2021-07-14 11:59 UTC, mativanarquero commented on src/pages/Home/AboutSection/config.ts
> +        guaranteedAllocation: 'Yes',
Oops! Done did it, will push first thing tomorrow morning. Thank you.

2021-07-15 01:00 UTC, mativanarquero commented on src/pages/Home/AboutSection/config.ts
> +        guaranteedAllocation: 'Yes',
Done po sir. Pacheck nalang po. Thank you.

2021-07-15 01:01 UTC, swengr-janan commented on src/pages/Home/AboutSection/config.ts
> +        guaranteedAllocation: 'Yes',
AGITH!

2021-07-15 01:02 UTC, swengr-janan approved these changes
All goods!

2021-07-15 01:03 UTC, merged